### ISSUE TITLE
Create repository class when create entity and selected "declare repository"

### ISSUE THREAD

**Issue by Koc** [nbphpcouncil/nb-symfony-templates-plugin#1]
Repository declared but PHP class with it doesn't created

**Comment by junichi11** [comment]
@Monomachus 
Probably, we can fix it. If you write details, I'll fix it and send a PR.

**Comment by Monomachus** [comment]
@junichi11 actually it is about New Entity Wizard, in the wizard when creating new entity you can check a checkbox to include the repository declaration. 

But until now I didn't create the repository as well, for various reasons,  seems it can be interesting for people, so I do it in this [file](https://github.com/nbphpcouncil/nb-symfony-templates-plugin/blob/master/src/org/nbphpcouncil/modules/php/symfony2/filetemplates/Symfony2EntityWizardIterator.java#L51), method *__instantiate__*.

I've pushed the template in PHP to *pr-1* branch, could you please take a look at it and let me know if you need anything else?

Thank you

**Comment by junichi11** [comment]
@Monomachus I'll push some changes in pr-1 branch.

> File also needs to be created in the right folder (we can determine the folder for repository from namespace for repository)

Is there an example?

**Comment by Monomachus** [comment]
yes actually I'm determining the folder here:

```java
 if (isRepositoryDeclared){
            args.put("namespaceForRepository", FileTemplatesUtils.getNamespaceForRepository(namespace));
        }
```
So you would need to use that variable to know where to generate it.

**Comment by junichi11** [comment]
@Monomachus I've fixed in the pr-1 branch. Could you have a look at it?

**Comment by Monomachus** [comment]
@junichi11 solved this one, once again :sunglasses:
